# Generated by Django 6.1 on 2026-08-23 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_restaurant_rate_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.dish'),
        ),
    ]
