# Generated by Django 6.0.4 on 2026-08-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_text_review_content_review_media_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
